services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    image: mariadb 
    restart: always
    env_file: 
      - .env
    networks:
      - inception
    volumes:
      - mariadb:/var/lib/mysql
#TODO: check why other have more stuff for image.

  nginx:
    container_name: nginx
    build: ./requirements/nginx
    image: nginx
    restart: always
    env_file: 
      - .env
    depends_on:
      - wordpress
    ports:
      - "443:443"
    networks:
      - inception
    volumes:
      - wordpress:/var/www/html

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    image: wordpress
    restart: always
    env_file: 
      - .env
    depends_on:
      - mariadb
    networks:
      - inception
    volumes:
      - wordpress:/var/www/html

networks:
  inception:
    driver: bridge

volumes:
  mariadb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${LOGIN}/data/mariadb
  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${LOGIN}/data/wordpress
